# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "786624c4fb5cded6a489253c94a07153"
name = "bitcube-discount"
handle = "bitcube-discount"
application_url = "https://notify-exact-ampland-modern.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-ad46e5d7.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://notify-exact-ampland-modern.trycloudflare.com/auth/callback",
  "https://notify-exact-ampland-modern.trycloudflare.com/auth/shopify/callback",
  "https://notify-exact-ampland-modern.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
